version: "2"

services:
  log-shipper:
    build: .
    links:
      - elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana:5.2.2
    ports:
      - 5601:5601
    links:
      - elasticsearch
    environment:
      - xpack.security.enabled=false
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.2
    ports:
      - 9200:9200
    environment:
      - xpack.security.enabled=false
